pool:
  vmImage: 'ubuntu-16.04'

- job: Test

  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npx tslint --project .
      npm test

- job: Publish
  dependsOn: Test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/tags/*'))
  steps:
  - task: NodeTool@1
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      versionSpec: '10.x'
  - script: |
      echo "//registry.npmjs.org/:_authToken=$SYSTEM_ACCESSTOKEN" > ~/.npmrc
      npm install
      npm publish

