jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npx tslint --project .
      npm test

- job: Publish
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: Test
  condition: and(succeeded(), and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), not(contains(variables['Build.SourceBranch'], '-'))))
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install
  - task: Npm@1
    inputs:
        command: Custom
        customCommand: version
        publishRegistry: useExternalRegistry
        publishEndpoint: npmjs
- job: PublishNext
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: Test
  condition: and(succeeded(), and(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), contains(variables['Build.SourceBranch'], '-')))
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install
  - task: Npm@1
    inputs:
        command: Custom
        customCommand: publish --tag next
        publishRegistry: useExternalRegistry
        publishEndpoint: npmjs

