import { expect } from 'chai'
import 'mocha'
import * as PropertyTypes from './constants'
import { IntegerAutogenerateOptions, IntegerPropertyType } from './IntegerPropertyType'

describe('IntegerAutogenerateOptions', () => {
  describe('constructor', () => {
    it('Should correctly assign Seed and Increment values', () => {
      expect(new IntegerAutogenerateOptions(13, 42)).to.deep.include({ Seed: 13, Increment: 42 })
    })
  })
})

describe('IntegerPropertyType', () => {
  describe('constructor', () => {
    it('Should return a PropertyType with a type name of Integer', () => {
      expect(new IntegerPropertyType({}).TypeName).to.equal(PropertyTypes.Integer)
    })
    it('Should use the supplied autogenerated options', () => {
      const autoOptions = new IntegerAutogenerateOptions(13, 42)
      expect(new IntegerPropertyType({ Autogenerate: autoOptions })).to.deep.include({
        Autogenerate: autoOptions
      })
    })
  })
})
