import {expect} from 'chai'
import 'mocha'
import constants from './constants'
import IntegerPropertyType, { IntegerAutogenerateOptions } from './IntegerPropertyType'

describe('IntegerAutogenerateOptions', () => {
    describe('constructor', () => {
        it('Should correctly assign Seed and Increment values', () => {
            expect(new IntegerAutogenerateOptions(13, 42)).to.deep.include({Seed: 13, Increment: 42})
        })
    })
})

describe('IntegerPropertyType', () => {
    describe('constructor', () => {
        it('Should return a PropertyType with a type name of Integer', () => {
            expect(new IntegerPropertyType().TypeName).to.equal(constants.Integer)
        })
        it('Should use the supplied autogenerated options', () => {
            const autoOptions = new IntegerAutogenerateOptions(13, 42)
            expect(new IntegerPropertyType(undefined, undefined, autoOptions)).to.deep.include({Autogenerate: autoOptions})
        })
        it('Should disallow invalid autogenerateOptions', () => {
            expect(() => new IntegerPropertyType(undefined, undefined, 'this should fail')).to.throw(TypeError, /Expected auto options to be of type IntegerAutogenerateOptions, got this should fail/)
        })
    })
})
